// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuvUZT28fsL5FZQK4QSSovt9mi2DNEtWQ',
    appId: '1:556370069807:web:4b16d221cfe9aaff8279da',
    messagingSenderId: '556370069807',
    projectId: 'playlaterapps',
    authDomain: 'playlaterapps.firebaseapp.com',
    storageBucket: 'playlaterapps.firebasestorage.app',
    measurementId: 'G-7DLK5D62HC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD6mbJozFdvdbqX7XspnlKPUwdfgugBrI',
    appId: '1:556370069807:android:636af0c01c35a9b08279da',
    messagingSenderId: '556370069807',
    projectId: 'playlaterapps',
    storageBucket: 'playlaterapps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDauao7Cio1-6eLvM29iYKyh9h5UwVx7E8',
    appId: '1:556370069807:ios:ef68275de661fb548279da',
    messagingSenderId: '556370069807',
    projectId: 'playlaterapps',
    storageBucket: 'playlaterapps.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDauao7Cio1-6eLvM29iYKyh9h5UwVx7E8',
    appId: '1:556370069807:ios:ef68275de661fb548279da',
    messagingSenderId: '556370069807',
    projectId: 'playlaterapps',
    storageBucket: 'playlaterapps.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuvUZT28fsL5FZQK4QSSovt9mi2DNEtWQ',
    appId: '1:556370069807:web:b4bfaacb4b3e122c8279da',
    messagingSenderId: '556370069807',
    projectId: 'playlaterapps',
    authDomain: 'playlaterapps.firebaseapp.com',
    storageBucket: 'playlaterapps.firebasestorage.app',
    measurementId: 'G-H71H53D0HZ',
  );
}
